/**
 * 10 Farb-Presets für die Katalog-Darstellung.
 * Jeder Preset definiert alle 11 Farbfelder.
 */
export default [
  {
    name: 'Standard',
    description: 'Klassisch dunkelblau mit Teal-Akzent',
    colors: {
      color_primary: '#1B3A5C',
      color_accent: '#0D9488',
      color_sidebar: '#1B3A5C',
      color_button: '#0D9488',
      color_table_bg: '#f8fafc',
      color_table_stripe: '#f1f5f9',
      color_body_text: '#111827',
      color_header_bg: '#1B3A5C',
      color_header_text: '#ffffff',
      color_mobile_menu_bg: '#1B3A5C',
      color_mobile_menu_text: '#ffffff',
    },
  },
  {
    name: 'Ocean Breeze',
    description: 'Tiefblau mit frischem Cyan',
    colors: {
      color_primary: '#0C4A6E',
      color_accent: '#06B6D4',
      color_sidebar: '#0C4A6E',
      color_button: '#0891B2',
      color_table_bg: '#f0f9ff',
      color_table_stripe: '#e0f2fe',
      color_body_text: '#0C4A6E',
      color_header_bg: '#0C4A6E',
      color_header_text: '#e0f2fe',
      color_mobile_menu_bg: '#0C4A6E',
      color_mobile_menu_text: '#e0f2fe',
    },
  },
  {
    name: 'Forest Green',
    description: 'Natuerliches Dunkelgruen mit Smaragd',
    colors: {
      color_primary: '#14532D',
      color_accent: '#059669',
      color_sidebar: '#14532D',
      color_button: '#059669',
      color_table_bg: '#f0fdf4',
      color_table_stripe: '#dcfce7',
      color_body_text: '#14532D',
      color_header_bg: '#14532D',
      color_header_text: '#dcfce7',
      color_mobile_menu_bg: '#14532D',
      color_mobile_menu_text: '#dcfce7',
    },
  },
  {
    name: 'Sunset Warm',
    description: 'Warmes Terrakotta mit Orange-Akzent',
    colors: {
      color_primary: '#7C2D12',
      color_accent: '#EA580C',
      color_sidebar: '#7C2D12',
      color_button: '#EA580C',
      color_table_bg: '#FFF7ED',
      color_table_stripe: '#FFEDD5',
      color_body_text: '#431407',
      color_header_bg: '#7C2D12',
      color_header_text: '#FFEDD5',
      color_mobile_menu_bg: '#7C2D12',
      color_mobile_menu_text: '#FFEDD5',
    },
  },
  {
    name: 'Royal Purple',
    description: 'Elegantes Violett mit Gold-Akzent',
    colors: {
      color_primary: '#3B0764',
      color_accent: '#D97706',
      color_sidebar: '#3B0764',
      color_button: '#D97706',
      color_table_bg: '#FAF5FF',
      color_table_stripe: '#F3E8FF',
      color_body_text: '#1E1B4B',
      color_header_bg: '#3B0764',
      color_header_text: '#F3E8FF',
      color_mobile_menu_bg: '#3B0764',
      color_mobile_menu_text: '#F3E8FF',
    },
  },
  {
    name: 'Slate Modern',
    description: 'Modernes Anthrazit mit kuehlem Grau',
    colors: {
      color_primary: '#1E293B',
      color_accent: '#6366F1',
      color_sidebar: '#1E293B',
      color_button: '#6366F1',
      color_table_bg: '#F8FAFC',
      color_table_stripe: '#F1F5F9',
      color_body_text: '#1E293B',
      color_header_bg: '#0F172A',
      color_header_text: '#E2E8F0',
      color_mobile_menu_bg: '#0F172A',
      color_mobile_menu_text: '#E2E8F0',
    },
  },
  {
    name: 'Rose Garden',
    description: 'Dunkelrosa mit modernem Pink',
    colors: {
      color_primary: '#881337',
      color_accent: '#E11D48',
      color_sidebar: '#881337',
      color_button: '#E11D48',
      color_table_bg: '#FFF1F2',
      color_table_stripe: '#FFE4E6',
      color_body_text: '#1C1917',
      color_header_bg: '#881337',
      color_header_text: '#FFE4E6',
      color_mobile_menu_bg: '#881337',
      color_mobile_menu_text: '#FFE4E6',
    },
  },
  {
    name: 'Earth Tones',
    description: 'Warmbraun mit Olive-Akzent',
    colors: {
      color_primary: '#44403C',
      color_accent: '#A16207',
      color_sidebar: '#44403C',
      color_button: '#A16207',
      color_table_bg: '#FAFAF9',
      color_table_stripe: '#F5F5F4',
      color_body_text: '#292524',
      color_header_bg: '#44403C',
      color_header_text: '#FAFAF9',
      color_mobile_menu_bg: '#44403C',
      color_mobile_menu_text: '#FAFAF9',
    },
  },
  {
    name: 'Nordic Light',
    description: 'Helles Grau mit Eisblau',
    colors: {
      color_primary: '#475569',
      color_accent: '#0EA5E9',
      color_sidebar: '#475569',
      color_button: '#0EA5E9',
      color_table_bg: '#FFFFFF',
      color_table_stripe: '#F8FAFC',
      color_body_text: '#334155',
      color_header_bg: '#F1F5F9',
      color_header_text: '#334155',
      color_mobile_menu_bg: '#F1F5F9',
      color_mobile_menu_text: '#334155',
    },
  },
  {
    name: 'Midnight',
    description: 'Dunkler Modus mit Neon-Akzent',
    colors: {
      color_primary: '#111827',
      color_accent: '#10B981',
      color_sidebar: '#111827',
      color_button: '#10B981',
      color_table_bg: '#1F2937',
      color_table_stripe: '#1a2332',
      color_body_text: '#F3F4F6',
      color_header_bg: '#030712',
      color_header_text: '#D1FAE5',
      color_mobile_menu_bg: '#030712',
      color_mobile_menu_text: '#D1FAE5',
    },
  },
]
