/**
 * 10 Farb-Presets für die Katalog-Darstellung.
 * Jeder Preset definiert alle 11 Farbfelder.
 *
 * Hinweise:
 *  – color_table_bg wird intern als Seitenhintergrund (base-200) verwendet.
 *    Daher immer sehr neutral / fast-weiß halten.
 *  – color_header_text sollte maximalen Kontrast zum Header-BG haben.
 */
export default [
  {
    name: 'Standard',
    description: 'Klassisch dunkelblau mit Teal-Akzent',
    colors: {
      color_primary: '#1B3A5C',
      color_accent: '#0D9488',
      color_sidebar: '#1B3A5C',
      color_button: '#0D9488',
      color_table_bg: '#F8FAFC',
      color_table_stripe: '#F1F5F9',
      color_body_text: '#111827',
      color_header_bg: '#1B3A5C',
      color_header_text: '#FFFFFF',
      color_mobile_menu_bg: '#1B3A5C',
      color_mobile_menu_text: '#FFFFFF',
    },
  },
  {
    name: 'Ocean Breeze',
    description: 'Tiefblau mit frischem Cyan',
    colors: {
      color_primary: '#0C4A6E',
      color_accent: '#06B6D4',
      color_sidebar: '#0C4A6E',
      color_button: '#0891B2',
      color_table_bg: '#F8FDFF',
      color_table_stripe: '#F0F9FF',
      color_body_text: '#0F172A',
      color_header_bg: '#0C4A6E',
      color_header_text: '#FFFFFF',
      color_mobile_menu_bg: '#0C4A6E',
      color_mobile_menu_text: '#FFFFFF',
    },
  },
  {
    name: 'Forest Green',
    description: 'Natuerliches Dunkelgruen mit Smaragd',
    colors: {
      color_primary: '#14532D',
      color_accent: '#059669',
      color_sidebar: '#14532D',
      color_button: '#059669',
      color_table_bg: '#FAFDFB',
      color_table_stripe: '#F0FDF4',
      color_body_text: '#0F172A',
      color_header_bg: '#14532D',
      color_header_text: '#FFFFFF',
      color_mobile_menu_bg: '#14532D',
      color_mobile_menu_text: '#FFFFFF',
    },
  },
  {
    name: 'Sunset Warm',
    description: 'Warmes Terrakotta mit Orange-Akzent',
    colors: {
      color_primary: '#7C2D12',
      color_accent: '#EA580C',
      color_sidebar: '#7C2D12',
      color_button: '#EA580C',
      color_table_bg: '#FFFCFA',
      color_table_stripe: '#FFF7ED',
      color_body_text: '#1C1917',
      color_header_bg: '#7C2D12',
      color_header_text: '#FFFFFF',
      color_mobile_menu_bg: '#7C2D12',
      color_mobile_menu_text: '#FFFFFF',
    },
  },
  {
    name: 'Royal Purple',
    description: 'Elegantes Violett mit Gold-Akzent',
    colors: {
      color_primary: '#4C1D95',
      color_accent: '#D97706',
      color_sidebar: '#4C1D95',
      color_button: '#D97706',
      color_table_bg: '#FDFCFE',
      color_table_stripe: '#FAF5FF',
      color_body_text: '#1E1B4B',
      color_header_bg: '#3B0764',
      color_header_text: '#FFFFFF',
      color_mobile_menu_bg: '#3B0764',
      color_mobile_menu_text: '#FFFFFF',
    },
  },
  {
    name: 'Slate Modern',
    description: 'Modernes Anthrazit mit Indigo-Akzent',
    colors: {
      color_primary: '#1E293B',
      color_accent: '#6366F1',
      color_sidebar: '#1E293B',
      color_button: '#6366F1',
      color_table_bg: '#F8FAFC',
      color_table_stripe: '#F1F5F9',
      color_body_text: '#0F172A',
      color_header_bg: '#0F172A',
      color_header_text: '#FFFFFF',
      color_mobile_menu_bg: '#0F172A',
      color_mobile_menu_text: '#FFFFFF',
    },
  },
  {
    name: 'Rose Garden',
    description: 'Elegantes Rose mit klarem Kontrast',
    colors: {
      color_primary: '#9F1239',
      color_accent: '#E11D48',
      color_sidebar: '#9F1239',
      color_button: '#E11D48',
      color_table_bg: '#FEFCFD',
      color_table_stripe: '#FFF1F2',
      color_body_text: '#1C1917',
      color_header_bg: '#881337',
      color_header_text: '#FFFFFF',
      color_mobile_menu_bg: '#881337',
      color_mobile_menu_text: '#FFFFFF',
    },
  },
  {
    name: 'Earth Tones',
    description: 'Warmbraun mit Olive-Akzent',
    colors: {
      color_primary: '#44403C',
      color_accent: '#A16207',
      color_sidebar: '#44403C',
      color_button: '#A16207',
      color_table_bg: '#FAFAF9',
      color_table_stripe: '#F5F5F4',
      color_body_text: '#1C1917',
      color_header_bg: '#292524',
      color_header_text: '#FFFFFF',
      color_mobile_menu_bg: '#292524',
      color_mobile_menu_text: '#FFFFFF',
    },
  },
  {
    name: 'Nordic Light',
    description: 'Helles, luftiges Design mit Eisblau',
    colors: {
      color_primary: '#334155',
      color_accent: '#0EA5E9',
      color_sidebar: '#334155',
      color_button: '#0EA5E9',
      color_table_bg: '#FFFFFF',
      color_table_stripe: '#F8FAFC',
      color_body_text: '#1E293B',
      color_header_bg: '#F1F5F9',
      color_header_text: '#1E293B',
      color_mobile_menu_bg: '#F1F5F9',
      color_mobile_menu_text: '#1E293B',
    },
  },
  {
    name: 'Austrian Sun',
    description: 'Kraeftiges Marineblau mit warmem Gold-Akzent (Doka-Stil)',
    colors: {
      color_primary: '#1D4685',
      color_accent: '#F9DC3D',
      color_sidebar: '#1D4685',
      color_button: '#1D4685',
      color_table_bg: '#F5F5F5',
      color_table_stripe: '#EBEBEB',
      color_body_text: '#333333',
      color_header_bg: '#F9DC3D',
      color_header_text: '#1D4685',
      color_mobile_menu_bg: '#FFFFFF',
      color_mobile_menu_text: '#333333',
    },
  },
  {
    name: 'Austrian Sunset',
    description: 'Vollbreites Layout mit Gelb-Header und Blau-Sidebar (Doka DOPI-Stil)',
    colors: {
      color_primary: '#004588',
      color_accent: '#FFdd00',
      color_sidebar: '#004588',
      color_button: '#004588',
      color_table_bg: '#F5F5F5',
      color_table_stripe: '#EBEBEB',
      color_body_text: '#2B2B2B',
      color_header_bg: '#FFdd00',
      color_header_text: '#004588',
      color_mobile_menu_bg: '#FFFFFF',
      color_mobile_menu_text: '#004588',
    },
  },
  {
    name: 'Midnight',
    description: 'Dunkler Modus mit Neon-Akzent',
    colors: {
      color_primary: '#E5E7EB',
      color_accent: '#10B981',
      color_sidebar: '#E5E7EB',
      color_button: '#10B981',
      color_table_bg: '#111827',
      color_table_stripe: '#1F2937',
      color_body_text: '#F3F4F6',
      color_header_bg: '#030712',
      color_header_text: '#D1FAE5',
      color_mobile_menu_bg: '#030712',
      color_mobile_menu_text: '#D1FAE5',
    },
  },
]
