import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import App from './App.vue'
import router from './router'
import './assets/main.css'
import { productEditorRawText } from './locales/productEditorRawText.js'
import { chromeRawText } from './locales/chromeRawText.js'
import { routeTitlesRawText } from './locales/routeTitlesRawText.js'
import { productListRawText } from './locales/productListRawText.js'
import { dashboardRawText } from './locales/dashboardRawText.js'
import { searchRawText } from './locales/searchRawText.js'
import { watchlistHierarchyRawText } from './locales/watchlistHierarchyRawText.js'
import { mediaRawText } from './locales/mediaRawText.js'
import { rawTextMessageResolver } from './i18n/rawTextMessageResolver.js'

// i18n messages
const messages = {
  de: {
    nav: {
      quickSearch: 'Schnellsuche',
      search: 'Profisuche',
      products: 'Produkte',
      hierarchies: 'Hierarchien',
      attributes: 'Attribute',
      manufacturers: 'Hersteller',
      productTypes: 'Produkttypen',
      relationTypes: 'Produktbeziehungen',
      attributeTypes: 'Attributgruppen',
      attributeViews: 'Attribut-Sichten',
      valueLists: 'Wertelisten',
      formattingRules: 'Formatierungsregeln',
      dictionary: 'Wörterbuch',
      imports: 'Import',
      exports: 'Export',
      media: 'Medien',
      mediaUsageTypes: 'Bildtypen',
      prices: 'Preise',
      priceRegions: 'Preisregionen',
      translations: 'Übersetzungen',
      users: 'Benutzer',
      settings: 'Einstellungen',
      help: 'Hilfe',
    },
    common: {
      save: 'Speichern',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      create: 'Erstellen',
      edit: 'Bearbeiten',
      search: 'Suchen…',
      filter: 'Filtern',
      loading: 'Laden…',
      noResults: 'Keine Ergebnisse',
      confirm: 'Bestätigen',
      actions: 'Aktionen',
      status: 'Status',
      name: 'Name',
      description: 'Beschreibung',
      type: 'Typ',
      active: 'Aktiv',
      inactive: 'Inaktiv',
      draft: 'Entwurf',
      all: 'Alle',
      selected: '{count} ausgewählt',
      perPage: 'pro Seite',
      of: 'von',
      yes: 'Ja',
      no: 'Nein',
    },
    product: {
      sku: 'Artikelnummer',
      title: 'Produkte',
      newProduct: 'Neues Produkt',
      details: 'Details',
      attributes: 'Attribute',
      variants: 'Varianten',
      media: 'Medien',
      prices: 'Preise',
      relations: 'Beziehungen',
      preview: 'Vorschau',
      history: 'Historie',
      versions: 'Versionen',
      dataLanguage: 'Datensprache',
      translationExportImport: 'Übersetzungen Export/Import',
      sourceLang: 'Quellsprache',
      targetLang: 'Zielsprache',
      xliffImported: 'importiert',
      xliffSkipped: 'übersprungen',
      version: {
        create: 'Neue Version',
        activate: 'Aktivieren',
        schedule: 'Planen',
        cancelSchedule: 'Planung aufheben',
        revert: 'Wiederherstellen',
        compare: 'Vergleichen',
        changeReason: 'Änderungsgrund',
        publishAt: 'Freigabe am',
        draft: 'Entwurf',
        scheduled: 'Geplant',
        active: 'Aktiv',
        archived: 'Archiviert',
        noVersions: 'Noch keine Versionen vorhanden',
        selectTwo: 'Zwei Versionen zum Vergleichen auswählen',
        confirmActivate: 'Diese Version sofort aktivieren?',
        confirmRevert: 'Produkt auf diese Version zurücksetzen?',
        hierarchyNode: 'Hierarchie-Knoten',
        currentState: 'Aktueller Stand',
      },
    },
    hierarchy: {
      title: 'Hierarchien',
      newNode: 'Neuer Knoten',
      moveNode: 'Knoten verschieben',
      deleteConfirm: 'Knoten und alle Unterknoten löschen?',
    },
    productType: {
      title: 'Produkttypen',
      newProductType: 'Neuer Produkttyp',
    },
    relationType: {
      title: 'Produktbeziehungen',
      newRelationType: 'Neuer Beziehungstyp',
    },
    attributeView: {
      title: 'Attribut-Sichten',
      newView: 'Neue Sicht',
    },
    attributeType: {
      title: 'Attributgruppen',
      newType: 'Neue Attributgruppe',
    },
    attribute: {
      title: 'Attribute',
      newAttribute: 'Neues Attribut',
      dataType: 'Datentyp',
      required: 'Pflichtfeld',
      searchable: 'Suchbar',
      filterable: 'Filterbar',
      inherited: 'Vererbt von: {source}',
      overridden: 'Überschrieben',
    },
    import: {
      title: 'Import',
      uploadFile: 'Datei hochladen',
      validate: 'Validieren',
      execute: 'Ausführen',
      template: 'Vorlage herunterladen',
    },
    export: {
      title: 'Export',
      startExport: 'Export starten',
      mapping: 'Mapping',
      preview: 'Vorschau',
    },
    settings: {
      title: 'Einstellungen',
      language: 'Sprache',
      dataLanguages: 'Aktive Datensprachen',
      appearance: 'Darstellung',
      appearancePlaceholder: 'Weitere Einstellungen werden hier konfiguriert.',
      dangerZone: 'Gefahrenbereich',
      resetTitle: 'Datenmodell zurücksetzen',
      resetDescription: 'Löscht alle Produkte, Hierarchien, Attribute und zugehörige Daten unwiderruflich. Benutzer, Rollen und Berechtigungen bleiben erhalten.',
      resetButton: 'Datenmodell zurücksetzen…',
      resetConfirmPrompt: 'Geben Sie RESET ein, um das Zurücksetzen zu bestätigen.',
      resetExecute: 'Endgültig zurücksetzen',
      resetSuccess: 'Datenmodell wurde erfolgreich zurückgesetzt.',
      resetError: 'Fehler beim Zurücksetzen des Datenmodells.',
    },
    cmd: {
      placeholder: 'Wo finde ich…',
      noResults: 'Keine Ergebnisse gefunden',
      noResultsHint: 'Versuche einen anderen Begriff oder Synonym',
      recentlyUsed: 'Zuletzt verwendet',
      sections: {
        navigation: 'Navigation',
        actions: 'Aktionen',
        recent: 'Zuletzt verwendet',
        config: 'Konfiguration',
        admin: 'Administration',
        settings: 'Einstellungen',
      },
      desc: {
        dashboard: 'Übersicht, Statistiken und Schnellzugriff',
        cockpit: 'Fokussierter Arbeitsplatz (Single-Page)',
        cockpitLayouts: 'Cockpit-Konfiguration je Rolle',
        catalogPreview: 'Öffentliche Katalog-Vorschau',
        pluginSettings: 'Plugins verwalten und konfigurieren',
        connectorCanva: 'Canva-Connector für Design-Integration',
        connectorShopware: 'Shopware-Connector für Shop-Anbindung',
        connectorCloudinary: 'Cloudinary-Connector für Medien-CDN',
        connectorClaudeAi: 'Claude AI-Connector für KI-gestützte Textgenerierung',
        connectorDeepl: 'DeepL-Connector für automatische Übersetzungen',
        comparisonOperators: 'Vergleichsoperatoren und -gruppen für Produktvergleiche',
        translationJobs: 'Übersetzungsjobs erstellen, verwalten und freigeben',
        excelDesigner: 'Excel-Vorlagen und Spaltenzuordnungen gestalten',
        attributeMappings: 'Attribut-Zuordnungen zwischen Quell- und Zielschema verwalten',
        testRunner: 'Systemtests und Integrationstests ausführen',
        dbConsistency: 'Datenbank-Konsistenzprüfungen und Reparaturen',
        logs: 'Anwendungs-Logs und Fehlerprotokolle einsehen',
        quickSearch: 'Schnelle Suche über Produkte, Medien, Hierarchien und Attribute',
        search: 'Erweiterte Produktsuche mit Filtern, Attributen und PQL',
        products: 'Alle Produkte anzeigen, bearbeiten und verwalten',
        watchlist: 'Gemerkte Produkte und persönliche Auswahl',
        workflow: 'Offene Workflow-Aufgaben und Freigaben',
        hierarchies: 'Kategorien, Bäume und Produktzuordnungen',
        media: 'Bilder, Dokumente und Dateien verwalten',
        mediaUsageTypes: 'Bildtypen für verschiedene Kanäle definieren',
        reports: 'Berichte erstellen und auswerten',
        pdfTemplates: 'PDF-Vorlagen für Datenblätter gestalten',
        catalogTemplates: 'Katalog-Layouts und Vorlagen verwalten',
        apiDesigner: 'API-Endpunkte konfigurieren und testen',
        calendar: 'Geplante Aktionen und Termine im Kalender',
        projectDashboard: 'Projektfortschritt und Team-Übersicht',
        workflows: 'Workflow-Definitionen und Regeln verwalten',
        workflowStatuses: 'Workflow-Statuswerte definieren',
        teams: 'Teams zusammenstellen und verwalten',
        projects: 'Projekte anlegen und verfolgen',
        manufacturers: 'Hersteller und Marken pflegen',
        productTypes: 'Produkttypen und Schablonen definieren',
        relationTypes: 'Beziehungsarten zwischen Produkten festlegen',
        attributeViews: 'Sichten auf Attribute für verschiedene Rollen',
        attributeTypes: 'Attributgruppen für die Strukturierung',
        attributes: 'Produktmerkmale und Eigenschaften verwalten',
        valueLists: 'Vordefinierte Auswahllisten pflegen',
        formattingRules: 'Formatierungsregeln für Attributwerte (Export & Vorschau) verwalten',
        dictionary: 'Begriffe und Übersetzungshilfen verwalten',
        units: 'Maßeinheiten und Einheitengruppen definieren',
        prices: 'Preistypen und Preispflege',
        priceRegions: 'Regionale Preiszonen definieren',
        translations: 'Sprachversionen der Daten verwalten',
        imports: 'Daten aus CSV, Excel oder anderen Quellen laden',
        exports: 'Daten in verschiedene Formate exportieren',
        jsonExportImport: 'Konfiguration als JSON sichern oder laden',
        bmecatExportImport: 'BMEcat-Standard Import und Export',
        exportJobs: 'Automatisierte Export-Aufträge verwalten',
        catalogDemo: 'Vorschau des öffentlichen Produktkatalogs',
        settings: 'Sprache, Darstellung und Systemkonfiguration',
        users: 'Benutzerkonten und Zugänge verwalten',
        userAudit: 'Benutzeraktivitäten und Login-Protokoll',
        roles: 'Rollen und Berechtigungen konfigurieren',
        accessLinks: 'Einladungslinks für externe Benutzer',
        apiTester: 'API-Endpunkte direkt testen',
        database: 'Datenbank-Tabellen einsehen',
        journal: 'Änderungsprotokoll aller Datensätze',
        help: 'Dokumentation und Hilfe',
        newProduct: 'Ein neues Produkt anlegen',
        newAttribute: 'Ein neues Attribut erstellen',
        uploadFile: 'Datei für den Import hochladen',
      },
    },
    catalog: {
      title: 'Produktkatalog',
      search: 'Produkte suchen (Name, Artikelnr., EAN)\u2026',
      allCategories: 'Alle Kategorien',
      categories: 'Kategorien',
      products: 'Produkte',
      product: 'Produkt',
      noResults: 'Keine Produkte gefunden',
      noResultsHint: 'Versuchen Sie einen anderen Suchbegriff oder w\u00e4hlen Sie eine andere Kategorie.',
      gridView: 'Kachelansicht',
      listView: 'Listenansicht',
      wishlist: 'Merkliste',
      wishlistEmpty: 'Ihre Merkliste ist leer',
      wishlistEmptyHint: 'Klicken Sie auf das Herz-Symbol, um Produkte zu merken.',
      addToWishlist: 'Zur Merkliste hinzuf\u00fcgen',
      removeFromWishlist: 'Von Merkliste entfernen',
      clearWishlist: 'Merkliste leeren',
      productDetail: 'Produktdetail',
      sku: 'Artikelnummer',
      ean: 'EAN',
      price: 'Preis',
      description: 'Beschreibung',
      attributes: 'Merkmale',
      category: 'Kategorie',
      close: 'Schlie\u00dfen',
      backToCatalog: 'Zur\u00fcck zum Katalog',
      showing: 'Zeige',
      of: 'von',
      results: 'Ergebnisse',
      sortBy: 'Sortieren nach',
      sortName: 'Name',
      sortPrice: 'Preis',
      sortSku: 'Artikelnummer',
      sortNewest: 'Neueste',
      previous: 'Zur\u00fcck',
      next: 'Weiter',
      poweredBy: 'anyPIM',
      filters: 'Filter',
      clearAllFilters: 'Alle Filter zurücksetzen',
      showMore: 'Mehr anzeigen',
      showLess: 'Weniger',
      from: 'Von',
      to: 'Bis',
      searchValues: 'Suchen…',
      activeFilters: 'Aktive Filter',
      searchOverridesFilters: 'Suche übersteuert Filter',
    },
    assetCatalog: {
      title: 'Asset-Katalog',
      search: 'Assets suchen\u2026',
      allFolders: 'Alle Ordner',
      folders: 'Ordner',
      assets: 'Assets',
      noResults: 'Keine Assets gefunden',
      noResultsHint: 'Versuchen Sie einen anderen Suchbegriff oder w\u00e4hlen Sie einen anderen Ordner.',
      gridView: 'Kachelansicht',
      listView: 'Listenansicht',
      wishlist: 'Merkliste',
      wishlistEmpty: 'Ihre Merkliste ist leer',
      wishlistEmptyHint: 'Klicken Sie auf das Herz-Symbol, um Assets zu merken.',
      addToWishlist: 'Zur Merkliste hinzuf\u00fcgen',
      removeFromWishlist: 'Von Merkliste entfernen',
      clearWishlist: 'Merkliste leeren',
      downloadZip: 'Als ZIP herunterladen',
      assetDetail: 'Asset-Detail',
      metadata: 'Metadaten',
      fileName: 'Dateiname',
      fileSize: 'Dateigr\u00f6\u00dfe',
      dimensions: 'Abmessungen',
      usagePurpose: 'Verwendungszweck',
      usagePrint: 'Print',
      usageWeb: 'Web',
      usageBoth: 'Print & Web',
      download: 'Herunterladen',
      close: 'Schlie\u00dfen',
      showing: 'Zeige',
      of: 'von',
      results: 'Ergebnisse',
      sortBy: 'Sortieren nach',
      sortName: 'Name',
      sortDate: 'Datum',
      sortSize: 'Gr\u00f6\u00dfe',
      previous: 'Zur\u00fcck',
      next: 'Weiter',
      poweredBy: 'anyPIM',
      allTypes: 'Alle Typen',
      images: 'Bilder',
      documents: 'Dokumente',
      allUsage: 'Alle',
      description: 'Beschreibung',
      noFolders: 'Keine Ordner vorhanden',
      moreAssets: 'weitere Assets',
      loadingError: 'Fehler beim Laden',
      assetNotFound: 'Asset nicht gefunden',
      downloadFailed: 'Download fehlgeschlagen',
      details: 'Details',
      usedBy: 'Verwendet von',
      noProducts: 'Dieses Asset wird von keinem Produkt verwendet.',
      productName: 'Produktname',
      usageProof: 'Verwendungsnachweis',
      usageProducts: 'Produkte',
      usageCategories: 'Kategorien',
      usageNone: 'Dieses Asset wird aktuell nicht verwendet.',
    },
  },
  en: {
    nav: {
      quickSearch: 'Quick Search',
      search: 'Search',
      products: 'Products',
      hierarchies: 'Hierarchies',
      attributes: 'Attributes',
      manufacturers: 'Manufacturers',
      productTypes: 'Product Types',
      relationTypes: 'Product Relations',
      attributeTypes: 'Attribute Groups',
      attributeViews: 'Attribute Views',
      valueLists: 'Value Lists',
      formattingRules: 'Formatting Rules',
      dictionary: 'Dictionary',
      imports: 'Import',
      exports: 'Export',
      media: 'Media',
      mediaUsageTypes: 'Image Types',
      prices: 'Prices',
      priceRegions: 'Price Regions',
      translations: 'Translations',
      users: 'Users',
      settings: 'Settings',
      help: 'Help',
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      create: 'Create',
      edit: 'Edit',
      search: 'Search…',
      filter: 'Filter',
      loading: 'Loading…',
      noResults: 'No results',
      confirm: 'Confirm',
      actions: 'Actions',
      status: 'Status',
      name: 'Name',
      description: 'Description',
      type: 'Type',
      active: 'Active',
      inactive: 'Inactive',
      draft: 'Draft',
      all: 'All',
      selected: '{count} selected',
      perPage: 'per page',
      of: 'of',
      yes: 'Yes',
      no: 'No',
    },
    product: {
      sku: 'SKU',
      title: 'Products',
      newProduct: 'New Product',
      details: 'Details',
      attributes: 'Attributes',
      variants: 'Variants',
      media: 'Media',
      prices: 'Prices',
      relations: 'Relations',
      preview: 'Preview',
      history: 'History',
      versions: 'Versions',
      dataLanguage: 'Data language',
      translationExportImport: 'Translation Export/Import',
      sourceLang: 'Source language',
      targetLang: 'Target language',
      xliffImported: 'imported',
      xliffSkipped: 'skipped',
      version: {
        create: 'New Version',
        activate: 'Activate',
        schedule: 'Schedule',
        cancelSchedule: 'Cancel Schedule',
        revert: 'Restore',
        compare: 'Compare',
        changeReason: 'Change Reason',
        publishAt: 'Publish at',
        draft: 'Draft',
        scheduled: 'Scheduled',
        active: 'Active',
        archived: 'Archived',
        noVersions: 'No versions yet',
        selectTwo: 'Select two versions to compare',
        confirmActivate: 'Activate this version immediately?',
        confirmRevert: 'Revert product to this version?',
        hierarchyNode: 'Hierarchy Node',
        currentState: 'Current State',
      },
    },
    hierarchy: {
      title: 'Hierarchies',
      newNode: 'New Node',
      moveNode: 'Move Node',
      deleteConfirm: 'Delete node and all children?',
    },
    productType: {
      title: 'Product Types',
      newProductType: 'New Product Type',
    },
    relationType: {
      title: 'Product Relations',
      newRelationType: 'New Relation Type',
    },
    attributeView: {
      title: 'Attribute Views',
      newView: 'New View',
    },
    attributeType: {
      title: 'Attribute Groups',
      newType: 'New Attribute Group',
    },
    attribute: {
      title: 'Attributes',
      newAttribute: 'New Attribute',
      dataType: 'Data Type',
      required: 'Required',
      searchable: 'Searchable',
      filterable: 'Filterable',
      inherited: 'Inherited from: {source}',
      overridden: 'Overridden',
    },
    import: {
      title: 'Import',
      uploadFile: 'Upload File',
      validate: 'Validate',
      execute: 'Execute',
      template: 'Download Template',
    },
    export: {
      title: 'Export',
      startExport: 'Start Export',
      mapping: 'Mapping',
      preview: 'Preview',
    },
    settings: {
      title: 'Settings',
      language: 'Language',
      dataLanguages: 'Active Data Languages',
      appearance: 'Appearance',
      appearancePlaceholder: 'Additional settings will be configured here.',
      dangerZone: 'Danger Zone',
      resetTitle: 'Reset Data Model',
      resetDescription: 'Permanently deletes all products, hierarchies, attributes and related data. Users, roles and permissions are preserved.',
      resetButton: 'Reset Data Model…',
      resetConfirmPrompt: 'Type RESET to confirm the data model reset.',
      resetExecute: 'Reset permanently',
      resetSuccess: 'Data model has been reset successfully.',
      resetError: 'Failed to reset the data model.',
    },
    cmd: {
      placeholder: 'Where do I find…',
      noResults: 'No results found',
      noResultsHint: 'Try a different term or synonym',
      recentlyUsed: 'Recently used',
      sections: {
        navigation: 'Navigation',
        actions: 'Actions',
        recent: 'Recently Used',
        config: 'Configuration',
        admin: 'Administration',
        settings: 'Settings',
      },
      desc: {
        dashboard: 'Overview, statistics and quick access',
        cockpit: 'Focused single-page workspace',
        cockpitLayouts: 'Cockpit configuration per role',
        catalogPreview: 'Public catalog preview',
        pluginSettings: 'Manage and configure plugins',
        connectorCanva: 'Canva connector for design integration',
        connectorShopware: 'Shopware connector for shop integration',
        connectorCloudinary: 'Cloudinary connector for media CDN',
        connectorClaudeAi: 'Claude AI connector for AI-powered text generation',
        connectorDeepl: 'DeepL connector for automatic translation',
        comparisonOperators: 'Comparison operators and groups for product comparisons',
        translationJobs: 'Create, manage and approve translation jobs',
        excelDesigner: 'Design Excel templates and column mappings',
        attributeMappings: 'Manage attribute mappings between source and target schema',
        testRunner: 'Run system tests and integration tests',
        dbConsistency: 'Database consistency checks and repairs',
        logs: 'View application logs and error protocols',
        quickSearch: 'Quick search across products, media, hierarchies and attributes',
        search: 'Advanced product search with filters and PQL',
        products: 'View, edit and manage all products',
        watchlist: 'Bookmarked products and personal selection',
        workflow: 'Open workflow tasks and approvals',
        hierarchies: 'Categories, trees and product assignments',
        media: 'Manage images, documents and files',
        mediaUsageTypes: 'Define image types for different channels',
        reports: 'Create and analyze reports',
        pdfTemplates: 'Design PDF templates for data sheets',
        catalogTemplates: 'Manage catalog layouts and templates',
        apiDesigner: 'Configure and test API endpoints',
        calendar: 'Scheduled actions and dates in the calendar',
        projectDashboard: 'Project progress and team overview',
        workflows: 'Manage workflow definitions and rules',
        workflowStatuses: 'Define workflow status values',
        teams: 'Create and manage teams',
        projects: 'Create and track projects',
        manufacturers: 'Manage manufacturers and brands',
        productTypes: 'Define product types and templates',
        relationTypes: 'Define relation types between products',
        attributeViews: 'Attribute views for different roles',
        attributeTypes: 'Attribute groups for structuring',
        attributes: 'Manage product attributes and properties',
        valueLists: 'Manage predefined selection lists',
        formattingRules: 'Manage formatting rules for attribute values (export & preview)',
        dictionary: 'Manage terms and translation aids',
        units: 'Define measurement units and unit groups',
        prices: 'Price types and price management',
        priceRegions: 'Define regional price zones',
        translations: 'Manage data language versions',
        imports: 'Load data from CSV, Excel or other sources',
        exports: 'Export data to various formats',
        jsonExportImport: 'Backup or restore configuration as JSON',
        bmecatExportImport: 'BMEcat standard import and export',
        exportJobs: 'Manage automated export jobs',
        catalogDemo: 'Preview of the public product catalog',
        settings: 'Language, appearance and system configuration',
        users: 'Manage user accounts and access',
        userAudit: 'User activity and login audit trail',
        roles: 'Configure roles and permissions',
        accessLinks: 'Invitation links for external users',
        apiTester: 'Test API endpoints directly',
        database: 'View database tables',
        journal: 'Change log of all records',
        help: 'Documentation and help',
        newProduct: 'Create a new product',
        newAttribute: 'Create a new attribute',
        uploadFile: 'Upload a file for import',
      },
    },
    catalog: {
      title: 'Product Catalog',
      search: 'Search products (name, article no., EAN)\u2026',
      allCategories: 'All Categories',
      categories: 'Categories',
      products: 'Products',
      product: 'Product',
      noResults: 'No products found',
      noResultsHint: 'Try a different search term or select another category.',
      gridView: 'Grid View',
      listView: 'List View',
      wishlist: 'Wishlist',
      wishlistEmpty: 'Your wishlist is empty',
      wishlistEmptyHint: 'Click the heart icon to save products.',
      addToWishlist: 'Add to Wishlist',
      removeFromWishlist: 'Remove from Wishlist',
      clearWishlist: 'Clear Wishlist',
      productDetail: 'Product Detail',
      sku: 'SKU',
      ean: 'EAN',
      price: 'Price',
      description: 'Description',
      attributes: 'Attributes',
      category: 'Category',
      close: 'Close',
      backToCatalog: 'Back to Catalog',
      showing: 'Showing',
      of: 'of',
      results: 'results',
      sortBy: 'Sort by',
      sortName: 'Name',
      sortPrice: 'Price',
      sortSku: 'SKU',
      sortNewest: 'Newest',
      previous: 'Previous',
      next: 'Next',
      poweredBy: 'anyPIM',
      filters: 'Filters',
      clearAllFilters: 'Clear all filters',
      showMore: 'Show more',
      showLess: 'Show less',
      from: 'From',
      to: 'To',
      searchValues: 'Search…',
      activeFilters: 'Active filters',
      searchOverridesFilters: 'Search overrides filters',
    },
    assetCatalog: {
      title: 'Asset Catalog',
      search: 'Search assets\u2026',
      allFolders: 'All Folders',
      folders: 'Folders',
      assets: 'Assets',
      noResults: 'No assets found',
      noResultsHint: 'Try a different search term or select another folder.',
      gridView: 'Grid View',
      listView: 'List View',
      wishlist: 'Wishlist',
      wishlistEmpty: 'Your wishlist is empty',
      wishlistEmptyHint: 'Click the heart icon to save assets.',
      addToWishlist: 'Add to Wishlist',
      removeFromWishlist: 'Remove from Wishlist',
      clearWishlist: 'Clear Wishlist',
      downloadZip: 'Download as ZIP',
      assetDetail: 'Asset Detail',
      metadata: 'Metadata',
      fileName: 'File Name',
      fileSize: 'File Size',
      dimensions: 'Dimensions',
      usagePurpose: 'Usage Purpose',
      usagePrint: 'Print',
      usageWeb: 'Web',
      usageBoth: 'Print & Web',
      download: 'Download',
      close: 'Close',
      showing: 'Showing',
      of: 'of',
      results: 'results',
      sortBy: 'Sort by',
      sortName: 'Name',
      sortDate: 'Date',
      sortSize: 'Size',
      previous: 'Previous',
      next: 'Next',
      poweredBy: 'anyPIM',
      allTypes: 'All Types',
      images: 'Images',
      documents: 'Documents',
      allUsage: 'All',
      description: 'Description',
      noFolders: 'No folders available',
      moreAssets: 'more assets',
      loadingError: 'Loading error',
      assetNotFound: 'Asset not found',
      downloadFailed: 'Download failed',
      details: 'Details',
      usedBy: 'Used by',
      noProducts: 'This asset is not used by any product.',
      productName: 'Product name',
      usageProof: 'Where used',
      usageProducts: 'Products',
      usageCategories: 'Categories',
      usageNone: 'This asset is currently not used.',
    },
  },
}

// Rohtext-Uebersetzungen (Compiler-Transform-PoC, siehe vite-plugins/rawTextI18nTransform.js)
// flach in die bestehenden Sprachbloecke einmischen -- Keys sind komplette
// deutsche Phrasen, keine Kollision mit den strukturierten nav.*/common.*-Keys zu erwarten.
Object.assign(messages.de, productEditorRawText.de, chromeRawText.de, routeTitlesRawText.de, productListRawText.de, dashboardRawText.de, searchRawText.de, watchlistHierarchyRawText.de, mediaRawText.de);
Object.assign(messages.en, productEditorRawText.en, chromeRawText.en, routeTitlesRawText.en, productListRawText.en, dashboardRawText.en, searchRawText.en, watchlistHierarchyRawText.en, mediaRawText.en);

const i18n = createI18n({
  legacy: false,
  locale: import.meta.env.VITE_DEFAULT_LOCALE || 'de',
  fallbackLocale: 'en',
  messageResolver: rawTextMessageResolver,
  messages,
})

// PoC: ?lang=en zum Testen der Rohtext-Uebersetzung, ohne die gespeicherte
// Spracheinstellung des Nutzers zu veraendern (bewusst nicht in localStorage
// persistiert -- reiner Session-Override fuer diesen Aufruf).
const testLocale = new URLSearchParams(window.location.search).get('lang');
if (testLocale && Object.prototype.hasOwnProperty.call(messages, testLocale)) {
  i18n.global.locale.value = testLocale;
}

const app = createApp(App)
const pinia = createPinia()

app.use(pinia)
app.use(router)
app.use(i18n)

// Erst mounten, wenn der Router die Initial-Route aufgelöst hat — sonst ist
// route.matched beim ersten Render leer und die Admin-Shell (AppLayout) blitzt
// kurz auf, bevor auf eine öffentliche Route (z.B. /site/...) umgeschaltet wird.
router.isReady().then(() => {
  app.mount('#app')
})
