import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import App from './App.vue'
import router from './router'
import './assets/main.css'

// i18n messages
const messages = {
  de: {
    nav: {
      search: 'Suche',
      products: 'Produkte',
      hierarchies: 'Hierarchien',
      attributes: 'Attribute',
      valueLists: 'Wertelisten',
      imports: 'Import',
      exports: 'Export',
      media: 'Medien',
      prices: 'Preise',
      users: 'Benutzer',
      settings: 'Einstellungen',
    },
    common: {
      save: 'Speichern',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      create: 'Erstellen',
      edit: 'Bearbeiten',
      search: 'Suchen…',
      filter: 'Filtern',
      loading: 'Laden…',
      noResults: 'Keine Ergebnisse',
      confirm: 'Bestätigen',
      actions: 'Aktionen',
      status: 'Status',
      name: 'Name',
      description: 'Beschreibung',
      type: 'Typ',
      active: 'Aktiv',
      inactive: 'Inaktiv',
      draft: 'Entwurf',
      all: 'Alle',
      selected: '{count} ausgewählt',
      perPage: 'pro Seite',
      of: 'von',
      yes: 'Ja',
      no: 'Nein',
    },
    product: {
      sku: 'Artikelnummer',
      title: 'Produkte',
      newProduct: 'Neues Produkt',
      details: 'Details',
      attributes: 'Attribute',
      variants: 'Varianten',
      media: 'Medien',
      prices: 'Preise',
      relations: 'Beziehungen',
      preview: 'Vorschau',
      history: 'Historie',
    },
    hierarchy: {
      title: 'Hierarchien',
      newNode: 'Neuer Knoten',
      moveNode: 'Knoten verschieben',
      deleteConfirm: 'Knoten und alle Unterknoten löschen?',
    },
    attribute: {
      title: 'Attribute',
      newAttribute: 'Neues Attribut',
      dataType: 'Datentyp',
      required: 'Pflichtfeld',
      searchable: 'Suchbar',
      filterable: 'Filterbar',
      inherited: 'Vererbt von: {source}',
      overridden: 'Überschrieben',
    },
    import: {
      title: 'Import',
      uploadFile: 'Datei hochladen',
      validate: 'Validieren',
      execute: 'Ausführen',
      template: 'Vorlage herunterladen',
    },
    export: {
      title: 'Export',
      startExport: 'Export starten',
      mapping: 'Mapping',
      preview: 'Vorschau',
    },
    settings: {
      title: 'Einstellungen',
      language: 'Sprache',
      uiLanguage: 'UI-Sprache',
      dataLanguages: 'Aktive Datensprachen',
      appearance: 'Darstellung',
      appearancePlaceholder: 'Weitere Einstellungen werden hier konfiguriert.',
      dangerZone: 'Gefahrenbereich',
      resetTitle: 'Datenmodell zurücksetzen',
      resetDescription: 'Löscht alle Produkte, Hierarchien, Attribute und zugehörige Daten unwiderruflich. Benutzer, Rollen und Berechtigungen bleiben erhalten.',
      resetButton: 'Datenmodell zurücksetzen…',
      resetConfirmPrompt: 'Geben Sie RESET ein, um das Zurücksetzen zu bestätigen.',
      resetExecute: 'Endgültig zurücksetzen',
      resetSuccess: 'Datenmodell wurde erfolgreich zurückgesetzt.',
      resetError: 'Fehler beim Zurücksetzen des Datenmodells.',
    },
    cmd: {
      placeholder: 'Suche oder Befehl eingeben…',
      noResults: 'Keine Ergebnisse gefunden',
      sections: {
        navigation: 'Navigation',
        actions: 'Aktionen',
        recent: 'Zuletzt verwendet',
      },
    },
    catalog: {
      title: 'Produktkatalog',
      search: 'Produkte suchen\u2026',
      allCategories: 'Alle Kategorien',
      categories: 'Kategorien',
      products: 'Produkte',
      product: 'Produkt',
      noResults: 'Keine Produkte gefunden',
      noResultsHint: 'Versuchen Sie einen anderen Suchbegriff oder w\u00e4hlen Sie eine andere Kategorie.',
      gridView: 'Kachelansicht',
      listView: 'Listenansicht',
      wishlist: 'Merkliste',
      wishlistEmpty: 'Ihre Merkliste ist leer',
      wishlistEmptyHint: 'Klicken Sie auf das Herz-Symbol, um Produkte zu merken.',
      addToWishlist: 'Zur Merkliste hinzuf\u00fcgen',
      removeFromWishlist: 'Von Merkliste entfernen',
      clearWishlist: 'Merkliste leeren',
      productDetail: 'Produktdetail',
      sku: 'Artikelnummer',
      ean: 'EAN',
      price: 'Preis',
      description: 'Beschreibung',
      category: 'Kategorie',
      close: 'Schlie\u00dfen',
      backToCatalog: 'Zur\u00fcck zum Katalog',
      showing: 'Zeige',
      of: 'von',
      results: 'Ergebnisse',
      sortBy: 'Sortieren nach',
      sortName: 'Name',
      sortPrice: 'Preis',
      sortSku: 'Artikelnummer',
      sortNewest: 'Neueste',
      previous: 'Zur\u00fcck',
      next: 'Weiter',
      poweredBy: 'Publixx PIM',
    },
  },
  en: {
    nav: {
      search: 'Search',
      products: 'Products',
      hierarchies: 'Hierarchies',
      attributes: 'Attributes',
      valueLists: 'Value Lists',
      imports: 'Import',
      exports: 'Export',
      media: 'Media',
      prices: 'Prices',
      users: 'Users',
      settings: 'Settings',
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      create: 'Create',
      edit: 'Edit',
      search: 'Search…',
      filter: 'Filter',
      loading: 'Loading…',
      noResults: 'No results',
      confirm: 'Confirm',
      actions: 'Actions',
      status: 'Status',
      name: 'Name',
      description: 'Description',
      type: 'Type',
      active: 'Active',
      inactive: 'Inactive',
      draft: 'Draft',
      all: 'All',
      selected: '{count} selected',
      perPage: 'per page',
      of: 'of',
      yes: 'Yes',
      no: 'No',
    },
    product: {
      sku: 'SKU',
      title: 'Products',
      newProduct: 'New Product',
      details: 'Details',
      attributes: 'Attributes',
      variants: 'Variants',
      media: 'Media',
      prices: 'Prices',
      relations: 'Relations',
      preview: 'Preview',
      history: 'History',
    },
    hierarchy: {
      title: 'Hierarchies',
      newNode: 'New Node',
      moveNode: 'Move Node',
      deleteConfirm: 'Delete node and all children?',
    },
    attribute: {
      title: 'Attributes',
      newAttribute: 'New Attribute',
      dataType: 'Data Type',
      required: 'Required',
      searchable: 'Searchable',
      filterable: 'Filterable',
      inherited: 'Inherited from: {source}',
      overridden: 'Overridden',
    },
    import: {
      title: 'Import',
      uploadFile: 'Upload File',
      validate: 'Validate',
      execute: 'Execute',
      template: 'Download Template',
    },
    export: {
      title: 'Export',
      startExport: 'Start Export',
      mapping: 'Mapping',
      preview: 'Preview',
    },
    settings: {
      title: 'Settings',
      language: 'Language',
      uiLanguage: 'UI Language',
      dataLanguages: 'Active Data Languages',
      appearance: 'Appearance',
      appearancePlaceholder: 'Additional settings will be configured here.',
      dangerZone: 'Danger Zone',
      resetTitle: 'Reset Data Model',
      resetDescription: 'Permanently deletes all products, hierarchies, attributes and related data. Users, roles and permissions are preserved.',
      resetButton: 'Reset Data Model…',
      resetConfirmPrompt: 'Type RESET to confirm the data model reset.',
      resetExecute: 'Reset permanently',
      resetSuccess: 'Data model has been reset successfully.',
      resetError: 'Failed to reset the data model.',
    },
    cmd: {
      placeholder: 'Search or enter command…',
      noResults: 'No results found',
      sections: {
        navigation: 'Navigation',
        actions: 'Actions',
        recent: 'Recently Used',
      },
    },
    catalog: {
      title: 'Product Catalog',
      search: 'Search products\u2026',
      allCategories: 'All Categories',
      categories: 'Categories',
      products: 'Products',
      product: 'Product',
      noResults: 'No products found',
      noResultsHint: 'Try a different search term or select another category.',
      gridView: 'Grid View',
      listView: 'List View',
      wishlist: 'Wishlist',
      wishlistEmpty: 'Your wishlist is empty',
      wishlistEmptyHint: 'Click the heart icon to save products.',
      addToWishlist: 'Add to Wishlist',
      removeFromWishlist: 'Remove from Wishlist',
      clearWishlist: 'Clear Wishlist',
      productDetail: 'Product Detail',
      sku: 'SKU',
      ean: 'EAN',
      price: 'Price',
      description: 'Description',
      category: 'Category',
      close: 'Close',
      backToCatalog: 'Back to Catalog',
      showing: 'Showing',
      of: 'of',
      results: 'results',
      sortBy: 'Sort by',
      sortName: 'Name',
      sortPrice: 'Price',
      sortSku: 'SKU',
      sortNewest: 'Newest',
      previous: 'Previous',
      next: 'Next',
      poweredBy: 'Publixx PIM',
    },
  },
}

const i18n = createI18n({
  legacy: false,
  locale: import.meta.env.VITE_DEFAULT_LOCALE || 'de',
  fallbackLocale: 'en',
  messages,
})

const app = createApp(App)
const pinia = createPinia()

app.use(pinia)
app.use(router)
app.use(i18n)
app.mount('#app')
