import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import App from './App.vue'
import router from './router'
import './assets/main.css'

// i18n messages
const messages = {
  de: {
    nav: {
      search: 'Suche',
      products: 'Produkte',
      hierarchies: 'Hierarchien',
      attributes: 'Attribute',
      productTypes: 'Produkttypen',
      attributeTypes: 'Attributgruppen',
      valueLists: 'Wertelisten',
      imports: 'Import',
      exports: 'Export',
      media: 'Medien',
      mediaUsageTypes: 'Bildtypen',
      prices: 'Preise',
      users: 'Benutzer',
      settings: 'Einstellungen',
    },
    common: {
      save: 'Speichern',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      create: 'Erstellen',
      edit: 'Bearbeiten',
      search: 'Suchen…',
      filter: 'Filtern',
      loading: 'Laden…',
      noResults: 'Keine Ergebnisse',
      confirm: 'Bestätigen',
      actions: 'Aktionen',
      status: 'Status',
      name: 'Name',
      description: 'Beschreibung',
      type: 'Typ',
      active: 'Aktiv',
      inactive: 'Inaktiv',
      draft: 'Entwurf',
      all: 'Alle',
      selected: '{count} ausgewählt',
      perPage: 'pro Seite',
      of: 'von',
      yes: 'Ja',
      no: 'Nein',
    },
    product: {
      sku: 'Artikelnummer',
      title: 'Produkte',
      newProduct: 'Neues Produkt',
      details: 'Details',
      attributes: 'Attribute',
      variants: 'Varianten',
      media: 'Medien',
      prices: 'Preise',
      relations: 'Beziehungen',
      preview: 'Vorschau',
      history: 'Historie',
      versions: 'Versionen',
      version: {
        create: 'Neue Version',
        activate: 'Aktivieren',
        schedule: 'Planen',
        cancelSchedule: 'Planung aufheben',
        revert: 'Wiederherstellen',
        compare: 'Vergleichen',
        changeReason: 'Änderungsgrund',
        publishAt: 'Freigabe am',
        draft: 'Entwurf',
        scheduled: 'Geplant',
        active: 'Aktiv',
        archived: 'Archiviert',
        noVersions: 'Noch keine Versionen vorhanden',
        selectTwo: 'Zwei Versionen zum Vergleichen auswählen',
        confirmActivate: 'Diese Version sofort aktivieren?',
        confirmRevert: 'Produkt auf diese Version zurücksetzen?',
        hierarchyNode: 'Hierarchie-Knoten',
        currentState: 'Aktueller Stand',
      },
    },
    hierarchy: {
      title: 'Hierarchien',
      newNode: 'Neuer Knoten',
      moveNode: 'Knoten verschieben',
      deleteConfirm: 'Knoten und alle Unterknoten löschen?',
    },
    productType: {
      title: 'Produkttypen',
      newProductType: 'Neuer Produkttyp',
    },
    attributeType: {
      title: 'Attributgruppen',
      newType: 'Neue Attributgruppe',
    },
    attribute: {
      title: 'Attribute',
      newAttribute: 'Neues Attribut',
      dataType: 'Datentyp',
      required: 'Pflichtfeld',
      searchable: 'Suchbar',
      filterable: 'Filterbar',
      inherited: 'Vererbt von: {source}',
      overridden: 'Überschrieben',
    },
    import: {
      title: 'Import',
      uploadFile: 'Datei hochladen',
      validate: 'Validieren',
      execute: 'Ausführen',
      template: 'Vorlage herunterladen',
    },
    export: {
      title: 'Export',
      startExport: 'Export starten',
      mapping: 'Mapping',
      preview: 'Vorschau',
    },
    settings: {
      title: 'Einstellungen',
      language: 'Sprache',
      uiLanguage: 'UI-Sprache',
      dataLanguages: 'Aktive Datensprachen',
      appearance: 'Darstellung',
      appearancePlaceholder: 'Weitere Einstellungen werden hier konfiguriert.',
      dangerZone: 'Gefahrenbereich',
      resetTitle: 'Datenmodell zurücksetzen',
      resetDescription: 'Löscht alle Produkte, Hierarchien, Attribute und zugehörige Daten unwiderruflich. Benutzer, Rollen und Berechtigungen bleiben erhalten.',
      resetButton: 'Datenmodell zurücksetzen…',
      resetConfirmPrompt: 'Geben Sie RESET ein, um das Zurücksetzen zu bestätigen.',
      resetExecute: 'Endgültig zurücksetzen',
      resetSuccess: 'Datenmodell wurde erfolgreich zurückgesetzt.',
      resetError: 'Fehler beim Zurücksetzen des Datenmodells.',
    },
    cmd: {
      placeholder: 'Suche oder Befehl eingeben…',
      noResults: 'Keine Ergebnisse gefunden',
      sections: {
        navigation: 'Navigation',
        actions: 'Aktionen',
        recent: 'Zuletzt verwendet',
      },
    },
    catalog: {
      title: 'Produktkatalog',
      search: 'Produkte suchen\u2026',
      allCategories: 'Alle Kategorien',
      categories: 'Kategorien',
      products: 'Produkte',
      product: 'Produkt',
      noResults: 'Keine Produkte gefunden',
      noResultsHint: 'Versuchen Sie einen anderen Suchbegriff oder w\u00e4hlen Sie eine andere Kategorie.',
      gridView: 'Kachelansicht',
      listView: 'Listenansicht',
      wishlist: 'Merkliste',
      wishlistEmpty: 'Ihre Merkliste ist leer',
      wishlistEmptyHint: 'Klicken Sie auf das Herz-Symbol, um Produkte zu merken.',
      addToWishlist: 'Zur Merkliste hinzuf\u00fcgen',
      removeFromWishlist: 'Von Merkliste entfernen',
      clearWishlist: 'Merkliste leeren',
      productDetail: 'Produktdetail',
      sku: 'Artikelnummer',
      ean: 'EAN',
      price: 'Preis',
      description: 'Beschreibung',
      attributes: 'Merkmale',
      category: 'Kategorie',
      close: 'Schlie\u00dfen',
      backToCatalog: 'Zur\u00fcck zum Katalog',
      showing: 'Zeige',
      of: 'von',
      results: 'Ergebnisse',
      sortBy: 'Sortieren nach',
      sortName: 'Name',
      sortPrice: 'Preis',
      sortSku: 'Artikelnummer',
      sortNewest: 'Neueste',
      previous: 'Zur\u00fcck',
      next: 'Weiter',
      poweredBy: 'Publixx PIM',
    },
    assetCatalog: {
      title: 'Asset-Katalog',
      search: 'Assets suchen\u2026',
      allFolders: 'Alle Ordner',
      folders: 'Ordner',
      assets: 'Assets',
      noResults: 'Keine Assets gefunden',
      noResultsHint: 'Versuchen Sie einen anderen Suchbegriff oder w\u00e4hlen Sie einen anderen Ordner.',
      gridView: 'Kachelansicht',
      listView: 'Listenansicht',
      wishlist: 'Merkliste',
      wishlistEmpty: 'Ihre Merkliste ist leer',
      wishlistEmptyHint: 'Klicken Sie auf das Herz-Symbol, um Assets zu merken.',
      addToWishlist: 'Zur Merkliste hinzuf\u00fcgen',
      removeFromWishlist: 'Von Merkliste entfernen',
      clearWishlist: 'Merkliste leeren',
      downloadZip: 'Als ZIP herunterladen',
      assetDetail: 'Asset-Detail',
      metadata: 'Metadaten',
      fileName: 'Dateiname',
      fileSize: 'Dateigr\u00f6\u00dfe',
      dimensions: 'Abmessungen',
      usagePurpose: 'Verwendungszweck',
      usagePrint: 'Print',
      usageWeb: 'Web',
      usageBoth: 'Print & Web',
      download: 'Herunterladen',
      close: 'Schlie\u00dfen',
      showing: 'Zeige',
      of: 'von',
      results: 'Ergebnisse',
      sortBy: 'Sortieren nach',
      sortName: 'Name',
      sortDate: 'Datum',
      sortSize: 'Gr\u00f6\u00dfe',
      previous: 'Zur\u00fcck',
      next: 'Weiter',
      poweredBy: 'Publixx PIM',
      allTypes: 'Alle Typen',
      images: 'Bilder',
      documents: 'Dokumente',
      allUsage: 'Alle',
      description: 'Beschreibung',
      noFolders: 'Keine Ordner vorhanden',
      moreAssets: 'weitere Assets',
      loadingError: 'Fehler beim Laden',
      assetNotFound: 'Asset nicht gefunden',
      downloadFailed: 'Download fehlgeschlagen',
    },
  },
  en: {
    nav: {
      search: 'Search',
      products: 'Products',
      hierarchies: 'Hierarchies',
      attributes: 'Attributes',
      productTypes: 'Product Types',
      attributeTypes: 'Attribute Groups',
      valueLists: 'Value Lists',
      imports: 'Import',
      exports: 'Export',
      media: 'Media',
      mediaUsageTypes: 'Image Types',
      prices: 'Prices',
      users: 'Users',
      settings: 'Settings',
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      create: 'Create',
      edit: 'Edit',
      search: 'Search…',
      filter: 'Filter',
      loading: 'Loading…',
      noResults: 'No results',
      confirm: 'Confirm',
      actions: 'Actions',
      status: 'Status',
      name: 'Name',
      description: 'Description',
      type: 'Type',
      active: 'Active',
      inactive: 'Inactive',
      draft: 'Draft',
      all: 'All',
      selected: '{count} selected',
      perPage: 'per page',
      of: 'of',
      yes: 'Yes',
      no: 'No',
    },
    product: {
      sku: 'SKU',
      title: 'Products',
      newProduct: 'New Product',
      details: 'Details',
      attributes: 'Attributes',
      variants: 'Variants',
      media: 'Media',
      prices: 'Prices',
      relations: 'Relations',
      preview: 'Preview',
      history: 'History',
      versions: 'Versions',
      version: {
        create: 'New Version',
        activate: 'Activate',
        schedule: 'Schedule',
        cancelSchedule: 'Cancel Schedule',
        revert: 'Restore',
        compare: 'Compare',
        changeReason: 'Change Reason',
        publishAt: 'Publish at',
        draft: 'Draft',
        scheduled: 'Scheduled',
        active: 'Active',
        archived: 'Archived',
        noVersions: 'No versions yet',
        selectTwo: 'Select two versions to compare',
        confirmActivate: 'Activate this version immediately?',
        confirmRevert: 'Revert product to this version?',
        hierarchyNode: 'Hierarchy Node',
        currentState: 'Current State',
      },
    },
    hierarchy: {
      title: 'Hierarchies',
      newNode: 'New Node',
      moveNode: 'Move Node',
      deleteConfirm: 'Delete node and all children?',
    },
    productType: {
      title: 'Product Types',
      newProductType: 'New Product Type',
    },
    attributeType: {
      title: 'Attribute Groups',
      newType: 'New Attribute Group',
    },
    attribute: {
      title: 'Attributes',
      newAttribute: 'New Attribute',
      dataType: 'Data Type',
      required: 'Required',
      searchable: 'Searchable',
      filterable: 'Filterable',
      inherited: 'Inherited from: {source}',
      overridden: 'Overridden',
    },
    import: {
      title: 'Import',
      uploadFile: 'Upload File',
      validate: 'Validate',
      execute: 'Execute',
      template: 'Download Template',
    },
    export: {
      title: 'Export',
      startExport: 'Start Export',
      mapping: 'Mapping',
      preview: 'Preview',
    },
    settings: {
      title: 'Settings',
      language: 'Language',
      uiLanguage: 'UI Language',
      dataLanguages: 'Active Data Languages',
      appearance: 'Appearance',
      appearancePlaceholder: 'Additional settings will be configured here.',
      dangerZone: 'Danger Zone',
      resetTitle: 'Reset Data Model',
      resetDescription: 'Permanently deletes all products, hierarchies, attributes and related data. Users, roles and permissions are preserved.',
      resetButton: 'Reset Data Model…',
      resetConfirmPrompt: 'Type RESET to confirm the data model reset.',
      resetExecute: 'Reset permanently',
      resetSuccess: 'Data model has been reset successfully.',
      resetError: 'Failed to reset the data model.',
    },
    cmd: {
      placeholder: 'Search or enter command…',
      noResults: 'No results found',
      sections: {
        navigation: 'Navigation',
        actions: 'Actions',
        recent: 'Recently Used',
      },
    },
    catalog: {
      title: 'Product Catalog',
      search: 'Search products\u2026',
      allCategories: 'All Categories',
      categories: 'Categories',
      products: 'Products',
      product: 'Product',
      noResults: 'No products found',
      noResultsHint: 'Try a different search term or select another category.',
      gridView: 'Grid View',
      listView: 'List View',
      wishlist: 'Wishlist',
      wishlistEmpty: 'Your wishlist is empty',
      wishlistEmptyHint: 'Click the heart icon to save products.',
      addToWishlist: 'Add to Wishlist',
      removeFromWishlist: 'Remove from Wishlist',
      clearWishlist: 'Clear Wishlist',
      productDetail: 'Product Detail',
      sku: 'SKU',
      ean: 'EAN',
      price: 'Price',
      description: 'Description',
      attributes: 'Attributes',
      category: 'Category',
      close: 'Close',
      backToCatalog: 'Back to Catalog',
      showing: 'Showing',
      of: 'of',
      results: 'results',
      sortBy: 'Sort by',
      sortName: 'Name',
      sortPrice: 'Price',
      sortSku: 'SKU',
      sortNewest: 'Newest',
      previous: 'Previous',
      next: 'Next',
      poweredBy: 'Publixx PIM',
    },
    assetCatalog: {
      title: 'Asset Catalog',
      search: 'Search assets\u2026',
      allFolders: 'All Folders',
      folders: 'Folders',
      assets: 'Assets',
      noResults: 'No assets found',
      noResultsHint: 'Try a different search term or select another folder.',
      gridView: 'Grid View',
      listView: 'List View',
      wishlist: 'Wishlist',
      wishlistEmpty: 'Your wishlist is empty',
      wishlistEmptyHint: 'Click the heart icon to save assets.',
      addToWishlist: 'Add to Wishlist',
      removeFromWishlist: 'Remove from Wishlist',
      clearWishlist: 'Clear Wishlist',
      downloadZip: 'Download as ZIP',
      assetDetail: 'Asset Detail',
      metadata: 'Metadata',
      fileName: 'File Name',
      fileSize: 'File Size',
      dimensions: 'Dimensions',
      usagePurpose: 'Usage Purpose',
      usagePrint: 'Print',
      usageWeb: 'Web',
      usageBoth: 'Print & Web',
      download: 'Download',
      close: 'Close',
      showing: 'Showing',
      of: 'of',
      results: 'results',
      sortBy: 'Sort by',
      sortName: 'Name',
      sortDate: 'Date',
      sortSize: 'Size',
      previous: 'Previous',
      next: 'Next',
      poweredBy: 'Publixx PIM',
      allTypes: 'All Types',
      images: 'Images',
      documents: 'Documents',
      allUsage: 'All',
      description: 'Description',
      noFolders: 'No folders available',
      moreAssets: 'more assets',
      loadingError: 'Loading error',
      assetNotFound: 'Asset not found',
      downloadFailed: 'Download failed',
    },
  },
}

const i18n = createI18n({
  legacy: false,
  locale: import.meta.env.VITE_DEFAULT_LOCALE || 'de',
  fallbackLocale: 'en',
  messages,
})

const app = createApp(App)
const pinia = createPinia()

app.use(pinia)
app.use(router)
app.use(i18n)
app.mount('#app')
